#!/usr/bin/zsh

export RACK_ENV=production
export SERVER_NAME=api.rob.mx
export BUNDLE_GEMFILE=/domains/rob.mx/api/Gemfile
RAKEFILE=/domains/rob.mx/api/Rakefile
LOGFILE=/domains/rob.mx/logs/strava.log

/usr/local/bin/rake --rakefile $RAKEFILE strava:poll 2>&1 >> $LOGFILE
